// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sujnjgmzttjkostfjuyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1am5qZ216dHRqa29zdGZqdXl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNjI3MzYsImV4cCI6MjA2MTkzODczNn0.yoeTJRaIdu4xwPx0-RUwBBjz5IGqGqxQ2qPlx3XqLOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);